services:
  client:
    image: wildrent2023/wildrent-client
    command: sh -c "npm run build"
    volumes:
      - web-client-build:/app/build
    environment:
      - NODE_ENV=production
      - REACT_APP_BACK_URL=http://localhost:4000/graphql
  server:
    image: wildrent2023/wildrent-server    
    ports:
      - 4000:4000
      - 3001:3001
    expose:
      - 4000
      - 3001
    command: sh -c "npm run build && npm run prod"
    environment:
      - NODE_ENV=production
      - PORT= 4000
      - SECRET_KEY= secret    
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:15
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d wildrent -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wildrent
    ports:
      - 5432:5432
    volumes:
      - wildrent-data:/var/lib/postgresql/data
  adminer:
    image: adminer
    depends_on:
      - db
    restart: always
    ports:
      - 8080:8080
  nginx:
    image: nginx:1.21.3
    depends_on:
      - server
      - client
    restart: always
    ports:
      - ${GATEWAY_PORT:-8000}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - web-client-build:/web-client-build
      - ./logs:/var/log/nginx
volumes:
  wildrent-data:
  web-client-build:
