type DetailsUser {
  id: String
  birthday: String
  address: String
  firstname: String
  lastname: String
}

type Query {
  detailsUsers: [DetailsUser]
  detailsConnectUser: DetailsUser
}

type Mutation {
  updateDetailsUser(id: String!, infos: DetailsUserRegister!): DetailsUser
}

input DetailsUserRegister {
  birthday: String!
  address: String!
  firstname: String!
  lastname: String!
}



